# -*- coding: utf-8 -*-
"""Python-Basics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14YcHRdZ_3xepTzZYQfyBMQyoTPcTKHPV
"""

#Rolling the Dice
import random as random
while True:
  die_inp = input ("Yes(y)/No(n): ").lower()
  if(die_inp=='y'):
    random_=random.randint(1,6)
    print("The number is:",random_)
  elif(die_inp=='n'):
    break
  else:
    print("Invalid input.. Try again")

import random as random
random_=random.randint(1,100)
while True:
  try:
    my_num=int(input("Take a guess (1-100): "))
    if(random_>my_num):
      print("Too Low!")
    elif(random_<my_num):
      print("Too High!")
    else:
      print("You guessed the right number")
      break
  except ValueError:
    print("Enter a valid number")

#rock-paper-scissors
import random as r
choices = ('r','p','s')
emojis ={'r':'🪨','p':'📄','s':'✂️'}
cont='y'
def rps(a,b):
  if choiced == comp_choice:
    return "Tie\n"
  elif((choiced=='r'and comp_choice=='s') or
       (choiced=='p'and comp_choice=='r') or
       (choiced=='s'and comp_choice=='p')):
    return "You Win\n"
  else:
    return "You Lose\n"

while True and cont=='y':
  choiced = input("Rock - Paper - Scissors (r/p/s): ").lower()
  comp_choice = r.choice(choices)
  if(choiced=='r' or choiced=='p'or choiced =='s'):
    print(f"your-choice:{emojis[choiced]}\ncomp-choice:{emojis[comp_choice]}\n")
    print(rps(comp_choice,choiced))
    cont=input("want to continue (y/n): ").lower()
  else:
    print("Enter a valid choice - nigga!")